version: 0.2
           
phases:
  install:
    commands:
      - gem install bundler jekyll
      - gem install minima                  
  pre_build:
    commands:
      - jekyll --version
      - bundler --version
  build:
    commands:
      - cd jfic-web
      - export LC_CTYPE="utf-8"
      - echo $LC_CTYPE
      - bundle exec jekyll b
  post_build:
    commands:
      - cd _site
      - pwd
artifacts:
  files:
    - 'jfic-web/_site/**/*'
  name: jekyll-sample-artifacts
  discard-paths: no
