version: 0.2
           
phases:
  install:
    commands:
      - gem install bundler jekyll
  pre_build:
    commands:
      - jekyll --version
  build:
    commands:
      - cd jfic-web
      - jekyll b
  post_build:
    commands:
      - cd _site
      - pwd
artifacts:
  files:
    - 'jfic-web/_site/**/*'
  name: jekyll-sample-artifacts
  discard-paths: no
